[package]
name = "rain_interpreter_parser"
version = "0.1.0"
edition = "2021"
license = "CAL-1.0"
description = "Rain Interpreter Parser Rust Crate."
homepage = "https://github.com/rainlanguage/rain.interpreter"

[dependencies]
rain_interpreter_dispair = { workspace = true }
anyhow = "1.0.70"
