name: CI deployments
on:
  push:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network to deploy to'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PRIVATE_KEY || secrets.PRIVATE_KEY_DEV }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Report public key to make it easy to send funds for deployments
        run: cast wallet address "${DEPLOYMENT_KEY}"
      - name: Forge shallow install
        run: forge install --shallow
      - name: Forge deploy contracts to ${{ inputs.network }}
        env:
          CI_DEPLOY_RPC_URL: ${{ inputs.network == 'polygon' && secrets.CI_DEPLOY_POLYGON_RPC_URL || secrets.CI_DEPLOY_RPC_URL }}
          EXPLORER_VERIFICATION_KEY: ${{ secrets.EXPLORER_VERIFICATION_KEY }}
        # run: nix run .#deploy-dispair