name: Gas snapshot

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Gas snapshot
    # Most dev work is done on mac, and snapshots disagree between platforms.
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Prepare repo
        run: nix run

      - name: Install deps
        run: nix develop --command forge install --shallow

      - name: Check gas snapshots
        run: nix develop --command forge snapshot --check
