name: Tests

on: [push]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: Tests
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Prepare repo
        run: nix run

      - name: Install deps
        run: nix develop --command forge install --shallow

      - name: Run Forge fmt
        run: nix develop --command forge fmt --check

      - name: Run Forge tests
        run: nix develop --command forge test -vvv --gas-report
