on: [push]

name: test interpreter crate

jobs:
  check:
    name: interpreter crate test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Prepare Interpreter Crate
        run: nix run .#gen-artifacts
        working-directory: interpreter-rs
      
      - name: Test Crate
        uses: actions-rs/cargo@v1
        run: nix run .#test
        working-directory: interpreter-rs
      
      - name: Lint
        uses: actions-rs/cargo@v1
        run: nix run .#lint-check
        working-directory: interpreter-rs
